# Generated by Django 5.1.4 on 2025-01-12 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(null=True)),
                ('popularity', models.FloatField()),
                ('release_date', models.DateField(null=True)),
                ('budget', models.PositiveBigIntegerField()),
                ('revenue', models.PositiveBigIntegerField()),
                ('runtime', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('Rumored', 'Rumored'), ('Planned', 'Planned'), ('In Production', 'In Production'), ('Post Production', 'Post Production'), ('Released', 'Released'), ('Canceled', 'Canceled')], max_length=20)),
                ('tagline', models.TextField(null=True)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('poster_path', models.URLField(null=True)),
                ('backdrop_path', models.URLField(null=True)),
                ('credits', models.ManyToManyField(blank=True, to='movies.contributor')),
                ('genres', models.ManyToManyField(blank=True, to='movies.genre')),
                ('keywords', models.ManyToManyField(blank=True, to='movies.keyword')),
                ('original_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.language')),
                ('production_companies', models.ManyToManyField(blank=True, to='movies.company')),
                ('recommendations', models.ManyToManyField(blank=True, to='movies.movie')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
